//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QIC.Farm.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReport
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Writer { get; set; }
        public bool IsExpired { get; set; }
        public bool IsClosed { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
